/**
 * Contains all the LevelData's, maintains and inits any
 * @author Bence Dobos
 */

package flapo;

import flapo.LevelData;
import flash.display.Sprite;
import gamelib2d.TileSet;
import gamelib2d.Layer;

class LevelContainer 
{

	public var LevelDatas: Array<LevelData>;
	var maxLevel: Int;
	
	public function new() 
	{
		maxLevel = 1;
		var l: Int;
		LevelDatas = new Array<LevelData>();
		l = 0;
	/*	LevelDatas[l] = new LevelData();
		LevelDatas[l].AddTile(BackgroundInfo);
		LevelDatas[l].AddTile(BlocksInfo);
		*/
	}
	
	/*returns LevelData*/
	public function getLevel(levelnum: Int, screen: Sprite) : LevelData
	{
		if (levelnum<0 || levelnum>maxLevel)
			return null;
		var retval: LevelData;
		var tiles: TileSet;
		var layer: Layer;
		switch (levelnum)
		{
			case 0:
				retval = new LevelData();
				
				tiles = new TileSet (screen);
				tiles.init (new BackgroundInfo ());  // BackgroundInfo.hx is generated by Tile Studio
				layer = new Layer (screen);
				layer.init (tiles, new BackgroundMap1Info (), false, 1.0, 1.0, mrp_tile, mrp_tile, true, true);
				retval.TileSets.push(tiles);
				retval.Layers.push(layer);
				/*
				foregroundTiles = new TileSet (screen);
				foregroundTiles.init (new BlocksInfo ());		
				
				foregroundLayer2 = new Layer (screen);
				foregroundLayer2.init (foregroundTiles, new BlocksBlocks2Info (), true, 0.9, 0.9, mrp_tile, mrp_tile, true, true );
				var colortransform : ColorTransform;
				colortransform = new ColorTransform(0.6, 0.6, 0.6, 1, 0, 0, 0, 0);
				foregroundLayer2.setColorTransform(colortransform);
				
				foregroundLayer = new Layer (screen);
				foregroundLayer.init (foregroundTiles, new BlocksMap1Info (), true, 1.0, 1.0, mrp_tile, mrp_tile, true, true);
*/
				//delete colortransform;
				//colortransform = new ColorTransform(1, 1, 1, 0.6, 0, 0, 0, 0);
				//foregroundLayer.setColorTransform(colortransform
			default:
				retval = null;
		}
		return retval;
		//return LevelDatas[levelnum];
	}
	
}